/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.iscreate.op.service.rno.job.avro.proto;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface VmHostCtrlProtocolAvro {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"VmHostCtrlProtocolAvro\",\"namespace\":\"com.iscreate.op.service.rno.job.avro.proto\",\"types\":[{\"type\":\"record\",\"name\":\"VmCtrlRequest\",\"fields\":[{\"name\":\"cmdType\",\"type\":\"string\",\"default\":\"create\"},{\"name\":\"nodeType\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"vmName\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"nodeToken\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"cpu\",\"type\":\"int\",\"default\":\"1\"},{\"name\":\"memory\",\"type\":\"float\",\"default\":1024.0},{\"name\":\"disk\",\"type\":\"float\",\"default\":10240.0}]},{\"type\":\"record\",\"name\":\"VmCtrlResponse\",\"fields\":[{\"name\":\"isAccepted\",\"type\":\"boolean\"},{\"name\":\"progress\",\"type\":\"string\",\"default\":\"\"}]},{\"type\":\"record\",\"name\":\"VmInfo\",\"fields\":[{\"name\":\"nodeType\",\"type\":\"string\",\"default\":\"WorkerNode\"},{\"name\":\"createTime\",\"type\":\"long\"},{\"name\":\"startTime\",\"type\":\"long\"},{\"name\":\"isFixed\",\"type\":\"boolean\"},{\"name\":\"name\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"token\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"state\",\"type\":\"string\",\"default\":\"\"}]},{\"type\":\"record\",\"name\":\"VmInfoList\",\"fields\":[{\"name\":\"vmlist\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"VmInfo\"}]}]}],\"messages\":{\"createVm\":{\"request\":[{\"name\":\"request\",\"type\":\"VmCtrlRequest\"}],\"response\":\"VmCtrlResponse\"},\"listVm\":{\"request\":[],\"response\":\"VmInfoList\"},\"destroyVm\":{\"request\":[{\"name\":\"request\",\"type\":\"VmCtrlRequest\"}],\"response\":\"VmCtrlResponse\"},\"startVm\":{\"request\":[{\"name\":\"request\",\"type\":\"VmCtrlRequest\"}],\"response\":\"VmCtrlResponse\"},\"getVmState\":{\"request\":[{\"name\":\"vmName\",\"type\":\"string\"}],\"response\":\"string\"}}}");
  com.iscreate.op.service.rno.job.avro.proto.VmCtrlResponse createVm(com.iscreate.op.service.rno.job.avro.proto.VmCtrlRequest request) throws org.apache.avro.AvroRemoteException;
  com.iscreate.op.service.rno.job.avro.proto.VmInfoList listVm() throws org.apache.avro.AvroRemoteException;
  com.iscreate.op.service.rno.job.avro.proto.VmCtrlResponse destroyVm(com.iscreate.op.service.rno.job.avro.proto.VmCtrlRequest request) throws org.apache.avro.AvroRemoteException;
  com.iscreate.op.service.rno.job.avro.proto.VmCtrlResponse startVm(com.iscreate.op.service.rno.job.avro.proto.VmCtrlRequest request) throws org.apache.avro.AvroRemoteException;
  java.lang.CharSequence getVmState(java.lang.CharSequence vmName) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends VmHostCtrlProtocolAvro {
    public static final org.apache.avro.Protocol PROTOCOL = com.iscreate.op.service.rno.job.avro.proto.VmHostCtrlProtocolAvro.PROTOCOL;
    void createVm(com.iscreate.op.service.rno.job.avro.proto.VmCtrlRequest request, org.apache.avro.ipc.Callback<com.iscreate.op.service.rno.job.avro.proto.VmCtrlResponse> callback) throws java.io.IOException;
    void listVm(org.apache.avro.ipc.Callback<com.iscreate.op.service.rno.job.avro.proto.VmInfoList> callback) throws java.io.IOException;
    void destroyVm(com.iscreate.op.service.rno.job.avro.proto.VmCtrlRequest request, org.apache.avro.ipc.Callback<com.iscreate.op.service.rno.job.avro.proto.VmCtrlResponse> callback) throws java.io.IOException;
    void startVm(com.iscreate.op.service.rno.job.avro.proto.VmCtrlRequest request, org.apache.avro.ipc.Callback<com.iscreate.op.service.rno.job.avro.proto.VmCtrlResponse> callback) throws java.io.IOException;
    void getVmState(java.lang.CharSequence vmName, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
  }
}