/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.iscreate.op.service.rno.job.avro.proto;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class VmInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"VmInfo\",\"namespace\":\"com.iscreate.op.service.rno.job.avro.proto\",\"fields\":[{\"name\":\"nodeType\",\"type\":\"string\",\"default\":\"WorkerNode\"},{\"name\":\"createTime\",\"type\":\"long\"},{\"name\":\"startTime\",\"type\":\"long\"},{\"name\":\"isFixed\",\"type\":\"boolean\"},{\"name\":\"name\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"token\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"state\",\"type\":\"string\",\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence nodeType;
  @Deprecated public long createTime;
  @Deprecated public long startTime;
  @Deprecated public boolean isFixed;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence token;
  @Deprecated public java.lang.CharSequence state;

  /**
   * Default constructor.
   */
  public VmInfo() {}

  /**
   * All-args constructor.
   */
  public VmInfo(java.lang.CharSequence nodeType, java.lang.Long createTime, java.lang.Long startTime, java.lang.Boolean isFixed, java.lang.CharSequence name, java.lang.CharSequence token, java.lang.CharSequence state) {
    this.nodeType = nodeType;
    this.createTime = createTime;
    this.startTime = startTime;
    this.isFixed = isFixed;
    this.name = name;
    this.token = token;
    this.state = state;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return nodeType;
    case 1: return createTime;
    case 2: return startTime;
    case 3: return isFixed;
    case 4: return name;
    case 5: return token;
    case 6: return state;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: nodeType = (java.lang.CharSequence)value$; break;
    case 1: createTime = (java.lang.Long)value$; break;
    case 2: startTime = (java.lang.Long)value$; break;
    case 3: isFixed = (java.lang.Boolean)value$; break;
    case 4: name = (java.lang.CharSequence)value$; break;
    case 5: token = (java.lang.CharSequence)value$; break;
    case 6: state = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'nodeType' field.
   */
  public java.lang.CharSequence getNodeType() {
    return nodeType;
  }

  /**
   * Sets the value of the 'nodeType' field.
   * @param value the value to set.
   */
  public void setNodeType(java.lang.CharSequence value) {
    this.nodeType = value;
  }

  /**
   * Gets the value of the 'createTime' field.
   */
  public java.lang.Long getCreateTime() {
    return createTime;
  }

  /**
   * Sets the value of the 'createTime' field.
   * @param value the value to set.
   */
  public void setCreateTime(java.lang.Long value) {
    this.createTime = value;
  }

  /**
   * Gets the value of the 'startTime' field.
   */
  public java.lang.Long getStartTime() {
    return startTime;
  }

  /**
   * Sets the value of the 'startTime' field.
   * @param value the value to set.
   */
  public void setStartTime(java.lang.Long value) {
    this.startTime = value;
  }

  /**
   * Gets the value of the 'isFixed' field.
   */
  public java.lang.Boolean getIsFixed() {
    return isFixed;
  }

  /**
   * Sets the value of the 'isFixed' field.
   * @param value the value to set.
   */
  public void setIsFixed(java.lang.Boolean value) {
    this.isFixed = value;
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'token' field.
   */
  public java.lang.CharSequence getToken() {
    return token;
  }

  /**
   * Sets the value of the 'token' field.
   * @param value the value to set.
   */
  public void setToken(java.lang.CharSequence value) {
    this.token = value;
  }

  /**
   * Gets the value of the 'state' field.
   */
  public java.lang.CharSequence getState() {
    return state;
  }

  /**
   * Sets the value of the 'state' field.
   * @param value the value to set.
   */
  public void setState(java.lang.CharSequence value) {
    this.state = value;
  }

  /** Creates a new VmInfo RecordBuilder */
  public static com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder newBuilder() {
    return new com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder();
  }
  
  /** Creates a new VmInfo RecordBuilder by copying an existing Builder */
  public static com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder newBuilder(com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder other) {
    return new com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder(other);
  }
  
  /** Creates a new VmInfo RecordBuilder by copying an existing VmInfo instance */
  public static com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder newBuilder(com.iscreate.op.service.rno.job.avro.proto.VmInfo other) {
    return new com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder(other);
  }
  
  /**
   * RecordBuilder for VmInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<VmInfo>
    implements org.apache.avro.data.RecordBuilder<VmInfo> {

    private java.lang.CharSequence nodeType;
    private long createTime;
    private long startTime;
    private boolean isFixed;
    private java.lang.CharSequence name;
    private java.lang.CharSequence token;
    private java.lang.CharSequence state;

    /** Creates a new Builder */
    private Builder() {
      super(com.iscreate.op.service.rno.job.avro.proto.VmInfo.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing VmInfo instance */
    private Builder(com.iscreate.op.service.rno.job.avro.proto.VmInfo other) {
            super(com.iscreate.op.service.rno.job.avro.proto.VmInfo.SCHEMA$);
      if (isValidValue(fields()[0], other.nodeType)) {
        this.nodeType = data().deepCopy(fields()[0].schema(), other.nodeType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.createTime)) {
        this.createTime = data().deepCopy(fields()[1].schema(), other.createTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.startTime)) {
        this.startTime = data().deepCopy(fields()[2].schema(), other.startTime);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.isFixed)) {
        this.isFixed = data().deepCopy(fields()[3].schema(), other.isFixed);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.name)) {
        this.name = data().deepCopy(fields()[4].schema(), other.name);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.token)) {
        this.token = data().deepCopy(fields()[5].schema(), other.token);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.state)) {
        this.state = data().deepCopy(fields()[6].schema(), other.state);
        fieldSetFlags()[6] = true;
      }
    }

    /** Gets the value of the 'nodeType' field */
    public java.lang.CharSequence getNodeType() {
      return nodeType;
    }
    
    /** Sets the value of the 'nodeType' field */
    public com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder setNodeType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.nodeType = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'nodeType' field has been set */
    public boolean hasNodeType() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'nodeType' field */
    public com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder clearNodeType() {
      nodeType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'createTime' field */
    public java.lang.Long getCreateTime() {
      return createTime;
    }
    
    /** Sets the value of the 'createTime' field */
    public com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder setCreateTime(long value) {
      validate(fields()[1], value);
      this.createTime = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'createTime' field has been set */
    public boolean hasCreateTime() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'createTime' field */
    public com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder clearCreateTime() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'startTime' field */
    public java.lang.Long getStartTime() {
      return startTime;
    }
    
    /** Sets the value of the 'startTime' field */
    public com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder setStartTime(long value) {
      validate(fields()[2], value);
      this.startTime = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'startTime' field has been set */
    public boolean hasStartTime() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'startTime' field */
    public com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder clearStartTime() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'isFixed' field */
    public java.lang.Boolean getIsFixed() {
      return isFixed;
    }
    
    /** Sets the value of the 'isFixed' field */
    public com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder setIsFixed(boolean value) {
      validate(fields()[3], value);
      this.isFixed = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'isFixed' field has been set */
    public boolean hasIsFixed() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'isFixed' field */
    public com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder clearIsFixed() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder setName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.name = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'name' field */
    public com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder clearName() {
      name = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'token' field */
    public java.lang.CharSequence getToken() {
      return token;
    }
    
    /** Sets the value of the 'token' field */
    public com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder setToken(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.token = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'token' field has been set */
    public boolean hasToken() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'token' field */
    public com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder clearToken() {
      token = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'state' field */
    public java.lang.CharSequence getState() {
      return state;
    }
    
    /** Sets the value of the 'state' field */
    public com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder setState(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.state = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'state' field has been set */
    public boolean hasState() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'state' field */
    public com.iscreate.op.service.rno.job.avro.proto.VmInfo.Builder clearState() {
      state = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public VmInfo build() {
      try {
        VmInfo record = new VmInfo();
        record.nodeType = fieldSetFlags()[0] ? this.nodeType : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.createTime = fieldSetFlags()[1] ? this.createTime : (java.lang.Long) defaultValue(fields()[1]);
        record.startTime = fieldSetFlags()[2] ? this.startTime : (java.lang.Long) defaultValue(fields()[2]);
        record.isFixed = fieldSetFlags()[3] ? this.isFixed : (java.lang.Boolean) defaultValue(fields()[3]);
        record.name = fieldSetFlags()[4] ? this.name : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.token = fieldSetFlags()[5] ? this.token : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.state = fieldSetFlags()[6] ? this.state : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
